version: '3'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
    networks:
      - backend

networks:
  backend:
    external:
      name: proxy